# Generated by Django 4.1.3 on 2022-11-17 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('Entry Code', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player Name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('High Score', models.IntegerField()),
                ('Date of Leading', models.DateField()),
                ('Leader Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sketchup_backend.user')),
            ],
        ),
    ]
