# Generated by Django 4.1.3 on 2022-11-24 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sketchup_backend', '0004_rename_entry code_lobby_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='curr_drawer',
            field=models.CharField(default='NULL', max_length=64),
        ),
        migrations.AddField(
            model_name='player',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sketchup_backend.lobby'),
        ),
    ]
