# Generated by Django 4.1.3 on 2022-11-25 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketchup_backend', '0010_lobby_first_drawer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='lobby',
            name='creation_time',
            field=models.DateField(default=datetime.datetime(2022, 11, 25, 16, 57, 32, 942421), null=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='curr_drawer',
            field=models.CharField(default='null', max_length=64),
        ),
    ]
