# Generated by Django 4.1.3 on 2022-11-25 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketchup_backend', '0011_leaderboard_lobby_creation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 17, 38, 53, 672988), null=True),
        ),
    ]
