# Generated by Django 4.1.3 on 2022-11-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketchup_backend', '0012_alter_lobby_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='creation_time',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
